.TH ASSETS_PATH 3 "generalGameEngine" "Engine Manual" "Engine Manual"
.SH NAME
assets_path \- absolute path helper
.SH SYNOPSIS
.nf
.B #include \(dqassets.h\(dq
.BI "const char  * assets_path(const char *relative_path, char *buf, size_t n);"
.fi
.SH DESCRIPTION
absolute path helper
.SH MODULE
assets (src/engine/assets/assets.h)
.SH SEE ALSO
.BR assets_texture (3),
.BR assets_init (3),
.BR assets_unload_all (3),
.BR gge (1),
.BR gge\-scenes (7)
