.TH ASSETS_TEXTURE 3 "generalGameEngine" "Engine Manual" "Engine Manual"
.SH NAME
assets_texture \- "sprites/player.bmp"
.SH SYNOPSIS
.nf
.B #include \(dqassets.h\(dq
.BI "Texture     * assets_texture(const char *relative_path);"
.fi
.SH DESCRIPTION
"sprites/player.bmp"
.SH MODULE
assets (src/engine/assets/assets.h)
.SH SEE ALSO
.BR assets_path (3),
.BR assets_init (3),
.BR assets_unload_all (3),
.BR gge (1),
.BR gge\-scenes (7)
