.TH CUT_FADE_OUT_S 3 "generalGameEngine" "Engine Manual" "Engine Manual"
.SH NAME
CUT_FADE_OUT_S \- CutStep initializer: fade the screen to black over sec seconds
.SH SYNOPSIS
.nf
.B #include \(dqcutscene.h\(dq
.ft B
#define CUT_FADE_OUT_S(sec) { .kind = CUT_FADE_OUT, .duration = (sec) }
.ft R
.fi
.SH DESCRIPTION
CutStep initializer: fade the screen to black over sec seconds. The screen stays black until a CUT_FADE_IN_S step or the cutscene ends.
.SH MODULE
cutscene (src/engine/cutscene/cutscene.h)
.SH SEE ALSO
.BR CUT_FADE_IN_S (3),
.BR CutStep (3),
.BR gge\-api (7),
.BR gge (1)
