.TH DRAW_LINE 3 "generalGameEngine" "Engine Manual" "Engine Manual"
.SH NAME
draw_line \- Line between two points in logical pixels
.SH SYNOPSIS
.nf
.B #include \(dqdraw.h\(dq
.BI "void draw_line(float x1, float y1, float x2, float y2, Color c);"
.fi
.SH DESCRIPTION
Line between two points in logical pixels.
.SH MODULE
draw (src/engine/draw/draw.h)
.SH SEE ALSO
.BR draw_point (3),
.BR gge (1),
.BR gge\-scenes (7)
