.TH TIMER_START 3 "generalGameEngine" "Engine Manual" "Engine Manual"
.SH NAME
timer_start \- Start (or restart) a countdown of seconds
.SH SYNOPSIS
.nf
.B #include \(dqtween.h\(dq
.BI "void timer_start(Timer *t, float seconds);"
.fi
.SH DESCRIPTION
Start (or restart) a countdown of seconds. Restarting a running timer simply resets it.
.PP
This is a static inline function; it is defined in the header.
.SH MODULE
tween (src/engine/tween/tween.h)
.SH SEE ALSO
.BR timer_tick (3),
.BR Timer (3),
.BR gge\-api (7),
.BR gge (1)
